# Generated by Django 4.1.7 on 2023-04-04 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_post_commentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
