# Generated by Django 4.1.7 on 2023-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_commentrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
