# Generated by Django 4.1.7 on 2023-04-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score',
        ),
    ]
