# Generated by Django 4.1.7 on 2023-04-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
    ]
