# Generated by Django 4.1.7 on 2023-03-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faculty',
            new_name='school',
        ),
    ]
